config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :publishers
  resources :books
  resources :members
  resources :book_publishers
  resources :book_members
  get "home/index"
  root to: "home#index"
end

app/models/book_member.rb
# == Schema Information
#
# Table name: book_members
#
#  id          :bigint           not null, primary key
#  book_id     :bigint
#  member_id   :bigint
#  issue_date  :string
#  due_date    :string
#  return_date :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class BookMember < ApplicationRecord
    validates :issue_date, :due_date, presence: true

    belongs_to :book
    belongs_to :member
end

app/controllers/book_members_controller.rb
class BookMembersController < ApplicationController
    def new
        @books = Book.all
        @members = Member.all
    end

    def create
      @book_member = BookMember.new(bookm_params)
      begin
        if @book_member.save!
          redirect_to action: :index
          flash[:success] = 'BookMember has been saved successfully 🥳 ... '
        end
      rescue StandardError
        flash.now[:danger] = @book_member.errors.full_messages.to_s
        render new_book_member_path, status: :not_acceptable
      end
    end
  
    def index
      @book_member = BookMember.all
    end
  
    def show
      @book_member = BookMember.find(params[:id])
    end
  
    def update
      @book_member = BookMember.find(params[:id])
      begin
        if @book_member.update!(bookm_params)
          redirect_to action: :index
          flash[:success] = 'BookMember has been updated successfully 🥳 ... '
        end
      rescue StandardError
        flash.now[:danger] = @book_member.errors.full_messages.to_s
        render action: 'edit'
      end
    end
  
    def edit
      @book_member = BookMember.find(params[:id])
    end
  
    def destroy
      BookMember.find(params[:id]).destroy
      redirect_to action: :index
      flash[:success] = 'BookMember has been deleted successfully 🥳 ... '
    end

    private
    def bookm_params
      params.require(:book_member).permit(:book_id, :member_id, :issue_date, :due_date, :return_date)
    end
end

app/helpers/book_members_helper.rb
module BookMembersHelper
end

app/views/book_members/edit.html.erb
<h1> BOOKMEMBER </h1>
<%= form_for :book_member, url: book_member_path(@book_member), method: :patch do |c| %>
<p>
  <%= c.label :return_date %> <br>
  <%= c.text_field :return_date %>
</p>
<p>
  <%= c.submit %>
</p>
<% end %>

app/views/book_members/index.html.erb
<button> <%= link_to "CREATE A NEW BOOKMEMBER",new_book_member_path %> </button>
<table class= "table table-striped">
     <thead>
       <tr>
         <th> ID </th>
         <th> BOOK TITLE </th>
         <th> MEMBER INFO </th>
         <th> ISSUE DATE </th>
         <th> DUE DATE </th>
         <th> RETURN DATE </th>
         <th> EDIT </th>
         <th> DELETE </th>
       </tr>
     </thead>
     <% @book_member.each do |book_member| %> 
     <tbody>
       <tr>
         <td>  <%= book_member.id %></td> 
         <td>  <%= book_member.book.title %> </td>
         <td> <%= book_member.member.memb_info %> </td>
         <td> <%= book_member.issue_date %> </td>
         <td> <%= book_member.due_date %> </td>
         <td> <%= book_member.return_date %> </td>
         <td> <button> <%= link_to  "Edit", edit_book_member_path(book_member) %> </button> </td>
         <td> <button> <%= link_to  "delete", book_member_path(book_member),method: :delete %> </button> </td>
       </tr>
     </tbody> 
     <% end %>   
</table>

app/views/book_members/new.html.erb
<h1> BookMember </h1>
<%= form_for :book_member, url: {action: "create"} do |c| %>
<p>
  <%= c.label :issue_date %> <br>
  <%= c.text_field :issue_date %>
</p>
<p>
  <%= c.label :due_date %> <br>
  <%= c.text_field :due_date %>
</p>
<p>
  <%= c.label :book_id %>
  <%= collection_select(:book_member, :book_id, @books, :id, :title, prompt: true) %>
</p>
<p>
  <%= c.label :member_id %>
  <%= collection_select(:book_member, :member_id, @members, :id, :memb_info, prompt: true) %> 
</p>
<p>
  <%= c.submit %>
</p>
<% end %>