config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :publishers
  resources :books
  resources :members
  resources :book_publishers
  resources :book_members
  get "home/index"
  root to: "home#index"
end

app/models/book_publisher.rb
# == Schema Information
#
# Table name: book_publishers
#
#  id           :bigint           not null, primary key
#  book_id      :bigint
#  publisher_id :bigint
#  pub_date     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class BookPublisher < ApplicationRecord
    validates :pub_date, presence: true
    
    belongs_to :book
    belongs_to :publisher
end

app/controllers/book_publishers_controller.rb
class BookPublishersController < ApplicationController
    def new
        @books = Book.all
        @publishers = Publisher.all
    end

    def create
      @book_publisher = BookPublisher.new(bookp_params)
      begin
        if @book_publisher.save!
          redirect_to action: :index
          flash[:success] = 'BookPublisher has been saved successfully 🥳 ... '
        end
      rescue StandardError
        flash.now[:danger] = @book_publisher.errors.full_messages.to_s
        render new_book_publisher_path, status: :not_acceptable
      end
    end
  
    def index
      @book_publisher = BookPublisher.all
    end
  
    def show
      @book_publisher = BookPublisher.find(params[:id])
    end
  
    def update
      @book_publisher = BookPublisher.find(params[:id])
      begin
        if @book_publisher.update!(bookp_params)
          redirect_to action: :index
          flash[:success] = 'BookPublisher has been updated successfully 🥳 ... '
        end
      rescue StandardError
        flash.now[:danger] = @book_publisher.errors.full_messages.to_s
        render action: 'edit'
      end
    end
  
    def edit
      @book_publisher = BookPublisher.find(params[:id])
    end
  
    def destroy
      BookPublisher.find(params[:id]).destroy
      redirect_to action: :index
      flash[:success] = 'BookPublisher has been deleted successfully 🥳 ... '
    end

    private
    def bookp_params
      params.require(:book_publisher).permit(:pub_date, :publisher_id, :book_id)
    end
end

app/helpers/book_publishers_helper.rb
module BookPublishersHelper
end

app/views/book_publishers/edit.html.erb
<h1> BOOKPUBLISHER </h1>
<%= form_for :book_publisher , url: book_publisher_path(@book_publisher), method: :patch do |c| %>
<p>
  <%= c.label :pub_date %> <br>
  <%= c.text_field :pub_date %>
</p>
<p>
  <%= c.submit %>
</p>
<% end %>

app/views/book_publishers/index.html.erb
<button> <%= link_to "CREATE A NEW BOOKPUBLISHER",new_book_publisher_path %> </button>
<table class= "table table-striped">
     <thead>
       <tr>
         <th> ID </th>
         <th> BOOK TITLE </th>
         <th> PUBLISHER NAME </th>
         <th> PUBLISH_DATE </th>
         <th> EDIT </th>
         <th> DELETE </th>
       </tr>
     </thead>
     <% @book_publisher.each do |book_publisher| %> 
     <tbody>
       <tr>
         <td>  <%= book_publisher.id %></td> 
         <td>  <%= book_publisher.book.title %> </td>
         <td> <%= book_publisher.publisher.name %> </td>
         <td> <%= book_publisher.pub_date %> </td>
         <td> <button> <%= link_to  "Edit", edit_book_publisher_path(book_publisher) %> </button> </td>
         <td> <button> <%= link_to  "delete", book_publisher_path(book_publisher),method: :delete %> </button> </td>
       </tr>
     </tbody> 
     <% end %>   
</table>

app/views/book_publishers/new.html.erb
<h1> BookPublisher </h1>
<%= form_for :book_publisher, url: {action: "create"} do |c| %>
<p>
  <%= c.label :pub_date %> <br>
  <%= c.text_field :pub_date %>
</p>
<p>
  <%= c.label :book_id %>
  <%= collection_select(:book_publisher, :book_id, @books, :id, :title, prompt: true) %>
</p>
<p>
  <%= c.label :publisher_id %>
  <%= collection_select(:book_publisher, :publisher_id, @publishers, :id, :name, prompt: true) %> 
</p>
<p>
  <%= c.submit %>
</p>
<% end %>