config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :publishers
  resources :books
  resources :members
  resources :book_publishers
  resources :book_members
  get "home/index"
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class = "navbar">
      <%= link_to "HOME", home_index_path %>
      <%= link_to "PUBLISHER", publishers_path %>
      <%= link_to "BOOK", books_path %> 
      <%= link_to "BOOK_PUBLISHER", book_publishers_path %> 
      <%= link_to "MEMBER", members_path %>
      <%= link_to "BOOK_MEMBER", book_members_path %> 
    </div>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-container" role="alert">
        <%= value %>
        <button id="alert-close-btn" type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="closeAlert()">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
      <% end %>
      <script>
          function closeAlert(){
            const removeElements = (elms) => elms.forEach(el => el.remove());
            removeElements( document.querySelectorAll(".alert") );
          }
      </script>
    <%= yield %>
  </body>
</html>