config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :publishers
  resources :books
  resources :members
  resources :book_publishers
  resources :book_members
  get "home/index"
  root to: "home#index"
end

app/models/member.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: members
#
#  id          :bigint           not null, primary key
#  memb_info   :text
#  memb_type   :string
#  address     :string
#  attriName   :string
#  expiry_date :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Member < ApplicationRecord
  validates :memb_info, :memb_type, :address, :attriName, :expiry_date, presence: true

  has_many :book_members
  has_many :books, through: :book_members
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  def new; end

  def create
    @member = Member.new(member_params)
    begin
      if @member.save!
        redirect_to action: :index
        flash[:success] = 'Member has been saved successfully 🥳 ... '
      end
    rescue StandardError
      flash.now[:danger] = @member.errors.full_messages.to_s
      render new_member_path, status: :not_acceptable
    end
  end

  def index
    @member = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    begin
      if @member.update!(member_params)
        redirect_to action: :index
        flash[:success] = 'Member has been updated successfully 🥳 ... '
      end
    rescue StandardError
      flash.now[:danger] = @member.errors.full_messages.to_s
      render action: 'edit'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def destroy
    Member.find(params[:id]).destroy
    redirect_to action: :index
    flash[:success] = 'Member has been deleted successfully 🥳 ... '
  end

  private

  def member_params
    params.require(:member).permit(:memb_info, :memb_type, :address, :attriName, :expiry_date)
  end
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/views/members/edit.html.erb
<h1> Member </h1>
<%= form_for :member , url: member_path(@member), method: :patch do |c| %>
<p>
  <%= c.label :memb_info %> <br>
  <%= c.text_field :memb_info, value: @member.memb_info %>
</p>
<p>
  <%= c.label :memb_type %> <br>
  <%= c.text_field :memb_type, value: @member.memb_type %>
</p>
<p>
  <%= c.label :address %> <br>
  <%= c.text_field :address, value: @member.address %>
</p>
<p>
  <%= c.label :attriName %> <br>
  <%= c.text_field :attriName, value: @member.attriName %>
</p>
<p>
  <%= c.label :expiry_date %> <br>
  <%= c.text_field :expiry_date, value: @member.expiry_date %>
</p>
<p>
  <%= c.submit %>
</p>
<% end %>

app/views/members/index.html.erb
 <button> <%= link_to "CREATE A NEW MEMBER",new_member_path %> </button>
<table class= "table table-striped">
     <thead>
       <tr>
         <th> ID </th>
         <th> MEMB_INFO </th>
         <th> MEMB_TYPE </th>
         <th> ADDRESS </th>
         <th> ATTRINAME </th>
         <th> EXPIRY_DATE</th>
         <th> EDIT </th>
         <th> DELETE </th>
       </tr>
     </thead>
     <% @member.each do |member| %> 
     <tbody>
       <tr>
         <td>  <%= member.id %></td> 
         <td>  <%= member.memb_info %> </td>
         <td>  <%= member.memb_type %> </td>
         <td> <%= member.address %> </td>
         <td> <%= member.attriName %> </td>
         <td> <%= member.expiry_date %> </td>
         <td> <button> <%= link_to  "Edit", edit_member_path(member) %> </button> </td>
         <td> <button> <%= link_to  "delete", member_path(member),method: :delete %> </button> </td>
       </tr>
     </tbody> 
     <% end %>   
</table>

app/views/members/new.html.erb
<h1> Member </h1>
<%= form_for :member, url: {action: "create"} do |c| %>
<p>
  <%= c.label :memb_info %> <br>
  <%= c.text_field :memb_info %>
</p>
<p>
  <%= c.label :memb_type %> <br>
  <%= c.text_field :memb_type %>
</p>
<p>
  <%= c.label :address %> <br>
  <%= c.text_field :address %>
</p>
<p>
  <%= c.label :attriName %> <br>
  <%= c.text_field :attriName %>
</p>
<p>
  <%= c.label :expiry_date %> <br>
  <%= c.text_field :expiry_date %>
</p>
<p>
  <%= c.submit %>
</p>
<% end %>